Fix packages for security
SkillsFundingAgency/das-qna-config pull request #29
Opened 2022-11-29 14:31 UTC by alandburns

2022-12-01 15:14 UTC, CodeWolf86 requested changes

2022-12-01 15:14 UTC, CodeWolf86 commented on components/project-builder/ListDraftSections.js
> +
did you mean to take out the <a> tags for the link creation?

2022-12-01 15:14 UTC, CodeWolf86 commented on pages/index.js
> +            legacyBehavior>
is this text required as part of the link?

2022-12-01 16:05 UTC, alandburns commented on components/project-builder/ListDraftSections.js
> +
The was done automatically to repair code to remove <a> tags so it can work with next.js by running
` npx @next/codemod new-link . --force`
 It does now work as expected - without this it failed to run.
 (I also checked with the author, and he agreed this was littered with legacy behavior links.

2023-01-05 08:52 UTC, ChrisJWoodcock approved these changes, later dismissed

2023-01-05 09:05 UTC, ChrisJWoodcock approved these changes

2023-01-05 09:25 UTC, merged